name: Build -> Test -> Publish Pipeline
on: [push]
jobs:

  build:
    name: "Build (& Publish)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/matthewbaggett/http-to-https-redirector
          target: redirector
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
